### PR TITLE
[WIP] Add feature: Maps faculty to courses

### PR DESCRIPTION
**Pull request by Shankusu993**
#40 
Added files for new feature which tells about which course was taught by which prof in which sem. Added json file containing data for 2018Autumn and a code file to update the json file in future.

### CODE REVIEW

**Comment by berserker1** [comment]
The data you are obtaining is of only previous sem right? or you can obtain from other sem also

**Comment by Ayushk4** [comment]
Try to shorten the name of the PR and commits. I think something like `Add feature: Maps faculty to courses` would be apt. Rest details could be in the description of the PR.

**Comment by Shankusu7** [comment]
@berserker1 

the data obtained by running the code file is the one which is currently hosted on the Hercules API. then it is stores(if its not already saved for the sem) alongside the already stored data in the same json file.


@Ayushk4 

ok , I will take care from next time .

**Comment by Ayushk4** [comment]
LGTM :+1: I will test this locally tomorrow and merge. 

@Shankusu7 Can you shorten the PR title?

**Pull request closed without merging**
